% --------- Kaplan Meier analysis
function kaplan_meier_data_analysis(filename_km, outputDir, numericData, ...
    geneNames, patientsNames, patientsNamesKM, timeData, cens, timeCutOff, ...
    structPatientsH, structPatientsL, gene_name, print_config)

% --------- Comparing patients with low gene expression vs. high in driver gene.

stats10 = KM_support_functions.get_log_rank_two_grps(patientsNamesKM,...
    timeData, cens, structPatientsH.h10, structPatientsL.l90, timeCutOff);

stats20 = KM_support_functions.get_log_rank_two_grps(patientsNamesKM,...
    timeData, cens, structPatientsH.h20, structPatientsL.l80, timeCutOff);

stats80 = KM_support_functions.get_log_rank_two_grps(patientsNamesKM,...
    timeData, cens, structPatientsH.h80, structPatientsL.l20, timeCutOff);

stats30 = KM_support_functions.get_log_rank_two_grps(patientsNamesKM, ...
    timeData, cens, structPatientsH.h30, structPatientsL.l70, timeCutOff);

stats70 = KM_support_functions.get_log_rank_two_grps(patientsNamesKM,...
    timeData, cens, structPatientsH.h70, structPatientsL.l30, timeCutOff);

if ~print_config.print_none
    title = KM_support_functions.create_title_plot_km_two_groups(...
        gene_name, 0.1, 0.9);
    KM_support_functions.plot_kaplan_meier_two_groups(patientsNamesKM,...
        timeData, cens, structPatientsH.h10, structPatientsL.l90,...
        title, stats10, gene_name); 
    
    title = KM_support_functions.create_title_plot_km_two_groups(...
        gene_name, 0.2, 0.8);
    KM_support_functions.plot_kaplan_meier_two_groups(patientsNamesKM,...
        timeData, cens, structPatientsH.h20, structPatientsL.l80,...
        title, stats20, gene_name);
    
    title = KM_support_functions.create_title_plot_km_two_groups(...
        gene_name, 0.8, 0.2);
    KM_support_functions.plot_kaplan_meier_two_groups(patientsNamesKM,...
        timeData, cens, structPatientsH.h80, structPatientsL.l20,...
        title, stats80, gene_name);
    
    title = KM_support_functions.create_title_plot_km_two_groups(...
        gene_name, 0.3, 0.7);
    KM_support_functions.plot_kaplan_meier_two_groups(patientsNamesKM,...
        timeData, cens, structPatientsH.h30, structPatientsL.l70,...
        title, stats30, gene_name);
    
    title = KM_support_functions.create_title_plot_km_two_groups(...
        gene_name, 0.7, 0.3);
    KM_support_functions.plot_kaplan_meier_two_groups(patientsNamesKM,...
        timeData, cens, structPatientsH.h70, structPatientsL.l30,...
        title, stats70, gene_name);
end
% -----------------------------------------------
% High 1st Gene (HG1), Low 1st Gene (LG1), High 2nd Gene (HG2),
% Low 2nd Gene (LG2) expressions with the following combinations: 
% HG1 + HG2, HG1 + LG2, LG1 + HG2, LG1 + LG2.
	
fileOutput = sprintf('KM_%sVsCandidateGenes_G1_H20_R80', gene_name);
KM_support_functions.kaplan_meier_gene1_vs_gene2_encapsulated(filename_km, fileOutput, outputDir, ...
	gene_name, numericData, patientsNames,structPatientsH.h20, structPatientsL.l80, patientsNamesKM,...
    geneNames, timeData, cens, timeCutOff, 0.2, 0.8, 'exp_exp', {stats20.p}, print_config);

fileOutput = sprintf('KM_%sVsCandidateGenes_G1_R80_L20', gene_name);
KM_support_functions.kaplan_meier_gene1_vs_gene2_encapsulated(filename_km, fileOutput, outputDir, ...
	gene_name, numericData, patientsNames, structPatientsH.h80, structPatientsL.l20, patientsNamesKM,...
    geneNames, timeData, cens, timeCutOff, 0.8, 0.2, 'exp_exp', {stats80.p}, print_config);

fileOutput = sprintf('KM_%sVsCandidateGenes_G1_H30_R70', gene_name);
KM_support_functions.kaplan_meier_gene1_vs_gene2_encapsulated(filename_km, fileOutput, outputDir, ...
	gene_name, numericData, patientsNames, structPatientsH.h30, structPatientsL.l70, patientsNamesKM,...
    geneNames, timeData, cens, timeCutOff, 0.3, 0.7, 'exp_exp', {stats30.p}, print_config);
	
fileOutput = sprintf('KM_%sVsCandidateGenes_G1_R70_L30', gene_name);
KM_support_functions.kaplan_meier_gene1_vs_gene2_encapsulated(filename_km, fileOutput, outputDir, ...
	gene_name, numericData, patientsNames, structPatientsH.h70, structPatientsL.l30, patientsNamesKM,...
    geneNames, timeData, cens, timeCutOff, 0.7, 0.3, 'exp_exp', {stats70.p}, print_config);

end