% --------- Kaplan Meier analysis
function kaplan_meier_data_analysis(filename_km, outputDir, numericData, ...
    geneNames, patientsNames, patientsNamesKM, timeData, cens, timeCutOff, ...
    structPatientsH, structPatientsL, gene_name)

% --------- Comparing patients with low gene expression vs. high.

title = sprintf('Kaplan Meier top 30%% %s vs 70%% low with log rank', gene_name);
stats30 = KM_support_functions.get_log_rank_two_grps(patientsNamesKM, ...
    timeData, cens, structPatientsH.h30, structPatientsL.l70, timeCutOff, title);
title = sprintf('Kaplan Meier top 20%% %s vs 80%% low with log rank', gene_name);
stats20 = KM_support_functions.get_log_rank_two_grps(patientsNamesKM,...
    timeData, cens, structPatientsH.h20, structPatientsL.l80, timeCutOff, title);
title = sprintf('Kaplan Meier top 10%% %s vs 90%% low with log rank', gene_name);
stats10 = KM_support_functions.get_log_rank_two_grps(patientsNamesKM,...
    timeData, cens, structPatientsH.h10, structPatientsL.l90, timeCutOff, title);
title = sprintf('Kaplan Meier top 80%% %s vs 20%% low with log rank', gene_name);
stats80 = KM_support_functions.get_log_rank_two_grps(patientsNamesKM,...
    timeData, cens, structPatientsH.h80, structPatientsL.l20, timeCutOff, title);
title = sprintf('Kaplan Meier top 70%% %s vs 30%% low with log rank', gene_name);
stats70 = KM_support_functions.get_log_rank_two_grps(patientsNamesKM,...
    timeData, cens, structPatientsH.h70, structPatientsL.l20, timeCutOff, title);

title = sprintf('Kaplan Meier top 30%% %s vs 70%% low', gene_name);
KM_support_functions.plot_kaplan_meier_two_groups(patientsNamesKM,...
    timeData, cens, structPatientsH.h30, structPatientsL.l70,...
    title, stats30, gene_name);
title = sprintf('Kaplan Meier top 20%% %s vs 80%% low', gene_name);
KM_support_functions.plot_kaplan_meier_two_groups(patientsNamesKM,...
    timeData, cens, structPatientsH.h20, structPatientsL.l80,...
    title, stats20, gene_name);
title = sprintf('Kaplan Meier top 10%% %s vs 90%% low', gene_name);
KM_support_functions.plot_kaplan_meier_two_groups(patientsNamesKM,...
    timeData, cens, structPatientsH.h10, structPatientsL.l90,...
    title, stats10, gene_name);
title = sprintf('Kaplan Meier top 80%% %s vs 20%% low', gene_name);
KM_support_functions.plot_kaplan_meier_two_groups(patientsNamesKM,...
    timeData, cens, structPatientsH.h80, structPatientsL.l20,...
    title, stats80, gene_name);
title = sprintf('Kaplan Meier top 70%% %s vs 30%% low', gene_name);
KM_support_functions.plot_kaplan_meier_two_groups(patientsNamesKM,...
    timeData, cens, structPatientsH.h70, structPatientsL.l30,...
    title, stats70, gene_name);

% -----------------------------------------------
% High 1st Gene (HG1), Low 1st Gene (LG1), High 2nd Gene (HG2),
% Low 2nd Gene (LG2) expressions with the following combinations: 
% HG1 + HG2, HG1 + LG2, LG1 + HG2, LG1 + LG2.
	
fileOutput = sprintf('KM_%sVsCandidateGenes_G1_H20_L80', gene_name);
KM_support_functions.kaplan_meier_gene1_vs_gene2_encapsulated(filename_km, fileOutput, outputDir, ...
	gene_name, numericData, patientsNames,structPatientsH.h20, structPatientsL.l80, patientsNamesKM,...
    geneNames, timeData, cens, timeCutOff, 0.2, 0.8, 'exp_exp', {stats20.p});

fileOutput = sprintf('KM_%sVsCandidateGenes_G1_H80_L20', gene_name);
KM_support_functions.kaplan_meier_gene1_vs_gene2_encapsulated(filename_km, fileOutput, outputDir, ...
	gene_name, numericData, patientsNames, structPatientsH.h80, structPatientsL.l20, patientsNamesKM,...
    geneNames, timeData, cens, timeCutOff, 0.8, 0.2, 'exp_exp', {stats80.p});

fileOutput = sprintf('KM_%sVsCandidateGenes_G1_H30_L70', gene_name);
KM_support_functions.kaplan_meier_gene1_vs_gene2_encapsulated(filename_km, fileOutput, outputDir, ...
	gene_name, numericData, patientsNames, structPatientsH.h30, structPatientsL.l70, patientsNamesKM,...
    geneNames, timeData, cens, timeCutOff, 0.3, 0.7, 'exp_exp', {stats30.p});
	
fileOutput = sprintf('KM_%sVsCandidateGenes_G1_H70_L30', gene_name);
KM_support_functions.kaplan_meier_gene1_vs_gene2_encapsulated(filename_km, fileOutput, outputDir, ...
	gene_name, numericData, patientsNames, structPatientsH.h70, structPatientsL.l30, patientsNamesKM,...
    geneNames, timeData, cens, timeCutOff, 0.7, 0.3, 'exp_exp', {stats70.p});

end